// Entire CLI extension for Pi
// Auto-generated by `entire enable --agent pi`
// Do not edit manually — changes will be overwritten on next install.
//
// Forwards Pi lifecycle events to `entire hooks pi <event>` so Entire can
// create checkpoints, capture transcripts, and offer rewind/resume.
//
// ENTIRE_CMD is replaced at install time by Entire's installer.

import { execFile } from "node:child_process";
import { once } from "node:events";

import { isToolCallEventType } from "@earendil-works/pi-coding-agent";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { Check } from "typebox/value";

const InjectedContextSchema = Type.Object(
  { inject_context: Type.Optional(Type.String()) },
  { additionalProperties: true }
);

interface SkillEvent {
  skill_name: string;
  invocation: string;
  timestamp: string;
}
interface EntireHookData {
  type:
    | "session_start"
    | "before_agent_start"
    | "agent_end"
    | "session_shutdown";
  cwd?: string;
  session_file?: string;
  prompt?: string;
  skill_events?: SkillEvent[];
}

const parseSkillInvocation = (
  text: string
): { skill_name: string; invocation: string } | null => {
  const match = /^\/skill:(?<skillName>[a-z0-9][a-z0-9-]{0,63})(?:\s|$)/u.exec(
    text.trimStart()
  );
  const skillName = match?.groups?.skillName;
  if (skillName === undefined || skillName === "") {
    return null;
  }
  const invocation =
    text.trimStart().split(/\s+/u, 1)[0] ?? `/skill:${skillName}`;
  return { invocation, skill_name: skillName };
};

const entireExtension = (pi: ExtensionAPI) => {
  // Herdr-launched subagents receive this dedicated flag because they do not
  // inherit the Parent Pi's environment. Pi preserves extension flag values
  // across /reload, so the owning process keeps the same identity after reload.
  pi.registerFlag("entire-nested", {
    default: false,
    description: "Disable top-level Entire lifecycle hooks in a nested Pi",
    type: "boolean",
  });
  const nested = pi.getFlag("entire-nested") === true;

  const ENTIRE_CMD = "entire";
  let pendingSkillEvents: SkillEvent[] = [];

  // fireHook pipes data to `entire hooks pi <hookName>` and resolves with the
  // hook's stdout (empty string on any failure). Most hooks ignore the return;
  // before_agent_start uses it to apply a model-context injection.
  const fireHook = async (
    hookName: string,
    data: EntireHookData
  ): Promise<string> => {
    let stdout = "";
    try {
      const child = execFile(
        "sh",
        ["-c", `${ENTIRE_CMD} hooks pi ${hookName}`],
        { maxBuffer: 4 * 1024 * 1024, timeout: 10_000, windowsHide: true },
        (_err, output) => {
          stdout = output;
        }
      );
      child.stdin?.end(JSON.stringify(data));
      await once(child, "close");
      return stdout;
    } catch {
      // best effort — never block the agent on a hook failure
      return "";
    }
  };

  // parseInjectedContext scans a hook's stdout for Entire's injection envelope
  // ({"inject_context":"..."}) and returns the text to inject, or null.
  const parseInjectedContext = (stdout: string): string | null => {
    if (!stdout) {
      return null;
    }
    for (const line of stdout.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed.startsWith("{")) {
        continue;
      }
      try {
        const parsed: unknown = JSON.parse(trimmed);
        if (
          Check(InjectedContextSchema, parsed) &&
          parsed.inject_context !== undefined &&
          parsed.inject_context !== ""
        ) {
          return parsed.inject_context;
        }
      } catch {
        // not our envelope — ignore
      }
    }
    return null;
  };

  // Agent-driven bash subprocesses inherit a real TTY but cannot answer
  // hook prompts. Disable git/Entire terminal prompts for bash calls so
  // Entire treats agent-driven commits as non-interactive.
  //
  // Registered even when nested: a nested Pi is non-interactive by construction
  // while still inheriting the parent's TTY, and Entire's git hooks live in
  // .git/hooks independently of this extension, so a nested subagent that commits
  // needs this hardening at least as much as the parent does.
  pi.on("tool_call", (event) => {
    if (
      !isToolCallEventType("bash", event) ||
      event.input.command.includes("GIT_TERMINAL_PROMPT=")
    ) {
      return;
    }
    event.input.command = `export GIT_TERMINAL_PROMPT=0\n${event.input.command}`;
  });

  // Everything below forwards session lifecycle to Entire, which only the
  // top-level Pi may do.
  if (nested) {
    return;
  }

  pi.on("input", (event) => {
    const skill = parseSkillInvocation(event.text);
    if (skill) {
      pendingSkillEvents.push({
        ...skill,
        timestamp: new Date().toISOString(),
      });
    }
    return { action: "continue" };
  });

  pi.on("session_start", async (_event, ctx) => {
    await fireHook("session_start", {
      cwd: ctx.cwd,
      session_file: ctx.sessionManager.getSessionFile(),
      type: "session_start",
    });
  });

  pi.on("before_agent_start", async (event, ctx) => {
    const skillEvents = pendingSkillEvents;
    pendingSkillEvents = [];
    const stdout = await fireHook("before_agent_start", {
      cwd: ctx.cwd,
      prompt: event.prompt,
      session_file: ctx.sessionManager.getSessionFile(),
      skill_events: skillEvents,
      type: "before_agent_start",
    });
    const injected = parseInjectedContext(stdout);
    return injected === null || injected === ""
      ? undefined
      : {
          // Inject a hidden, persistent message so the model learns about Entire.
          // display:false keeps it out of the user-facing transcript while still
          // sending it to the LLM. Entire emits this at most once per session.
          message: {
            content: injected,
            customType: "entire-context",
            display: false,
          },
        };
  });

  pi.on("agent_end", async (_event, ctx) => {
    await fireHook("agent_end", {
      cwd: ctx.cwd,
      session_file: ctx.sessionManager.getSessionFile(),
      type: "agent_end",
    });
  });

  pi.on("session_shutdown", async () => {
    await fireHook("session_shutdown", { type: "session_shutdown" });
  });
};

export default entireExtension;
